apiVersion: batch/v1
kind: Job 
metadata:
  name: terraformtester 
  namespace: cisco-terraform
  labels:
    argo.job: terraformtester 
spec:
  template:
    metadata:
      labels:
        argo.job: terraformtester 
      creationTimestamp: null
    spec:
      containers:
      - env:
        image: terraform-testsuite:v1
        imagePullPolicy: ""
        name: terraformtester
        resources: {}
      restartPolicy: Never 
  backoffLimit: 0
