apiVersion: v1
kind: Namespace
metadata:
  name: cisco-terraform
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: cisco-terraform
spec:
  type: ExternalName
  externalName: mongo-svc.argo-infra.svc.cluster.local
  ports:
  - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: cisco-terraform
spec:
  type: ExternalName
  externalName: kafka-svc.argo-infra.svc.cluster.local
  ports:
  - port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: clustermgr
  namespace: cisco-terraform
  labels:
    service: clustermgr
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30001
  selector:
    service: clustermgr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustermgr
  namespace: cisco-terraform
  labels:
    service: clustermgr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: clustermgr
  template:
    metadata:
      labels:
        service: clustermgr
    spec:
      restartPolicy: Always
      volumes:
      containers:
      - name: clustermgr
        image: clustermgr:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: ARGO_KAFKA_ADDR
            value: "kafka-svc:9092"
        ports:
        - containerPort: 8089
        command: ["/bin/cluster"]
        args: ["-config.file", "/bin/config_sanity.json"]
---
apiVersion: v1
kind: Service
metadata:
  name: nodemgr
  namespace: cisco-terraform
  labels:
    service: nodemgr
spec:
  type: NodePort
  ports:
    - port: 8089
      nodePort: 30000
  selector:
    service: nodemgr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemgr
  namespace: cisco-terraform
  labels:
    service: nodemgr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: nodemgr
  template:
    metadata:
      labels:
        service: nodemgr
    spec:
      restartPolicy: Always
      containers:
      - name: nodemgr
        image: nodemgr:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: ARGO_KAFKA_ADDR
            value: "kafka-svc:9092"
        ports:
        - containerPort: 8089
        command: ["/bin/node"]
        args: ["-config.file", "/bin/config_sanity.json"]
