apiVersion: case.cncf.io/v1
kind: App
metadata:
  name: cisco-terraform
spec:
  vendor: cisco
  app: terraform
  uiEntrypoint: /appcenter/cisco/terraform/ui/
  security:
    infraAccess:
      enabled: true
      autoRefresh: true
  deploymentFlavors:
  - name: default
    enableInjection: true
    storage:
    - storageID: logger
      size: 2Gi
      diskType: Any
    cpu:
      target:
      - resourceLabel: cpu-terraform
        request: "1"
        limit: "2"
    memory:
      target:
      - resourceLabel: memory-terraform
        request: 2Gi
        limit: 3Gi
  defaultFlavors:
  - caseDeploymentProfile: physical-standard
    flavor: default
  - caseDeploymentProfile: physical-small
    flavor: default
  - caseDeploymentProfile: default
    flavor: default
---
apiVersion: case.cncf.io/v1
kind: Certificate
metadata:
  name: cisco-terraform
  namespace: cisco-terraform
spec:
  services:
  - name: cisco-terraform-certs
    cn:
      name: cisco-terraform
      addNamespace: false
      addDomain: false
    sans:
      dnsnames:
      - "*"
    extensions:
      basicConstraints:
        ca: false
      extendedKeyUsage:
      - ServerAuth
      - ClientAuth
---
apiVersion: case.cncf.io/v1
kind: Kafka
metadata:
  name: kafka-topics
  namespace: cisco-terraform
spec:
 topics:
 - name: organization-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: organization-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agent-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agent-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agentpool-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agentpool-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: credentials-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: credentials-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 acls:
 - name: organization-topic-wr
   cn: cisco-terraform
   topic: organization-topic
   op: Write
 - name: organization-topic-rd
   cn: cisco-terraform
   topic: organization-topic
   op: Read
 - name: organization-manager-topic-wr
   cn: cisco-terraform
   topic: organization-manager-topic
   op: Write
 - name: organization-manager-topic-rd
   cn: cisco-terraform
   topic: organization-manager-topic
   op: Read
 - name: agent-topic-wr
   cn: cisco-terraform
   topic: agent-topic
   op: Write
 - name: agent-topic-rd
   cn: cisco-terraform
   topic: agent-topic
   op: Read
 - name: agent-manager-topic-wr
   cn: cisco-terraform
   topic: agent-manager-topic
   op: Write
 - name: agent-manager-topic-rd
   cn: cisco-terraform
   topic: agent-manager-topic
   op: Read
 - name: agentpool-topic-wr
   cn: cisco-terraform
   topic: agentpool-topic
   op: Write
 - name: agentpool-topic-rd
   cn: cisco-terraform
   topic: agentpool-topic
   op: Read
 - name: agentpool-manager-topic-wr
   cn: cisco-terraform
   topic: agentpool-manager-topic
   op: Write
 - name: agentpool-manager-topic-rd
   cn: cisco-terraform
   topic: agentpool-manager-topic
   op: Read
 - name: credentials-topic-wr
   cn: cisco-terraform
   topic: credentials-topic
   op: Write
 - name: credentials-topic-rd
   cn: cisco-terraform
   topic: credentials-topic
   op: Read
 - name: credentials-manager-topic-wr
   cn: cisco-terraform
   topic: credentials-manager-topic
   op: Write
 - name: credentials-manager-topic-rd
   cn: cisco-terraform
   topic: credentials-manager-topic
   op: Read
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kms
  namespace: cisco-terraform
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8-system-kms
---
apiVersion: case.cncf.io/v1
kind: APIGW
metadata:
  name: cisco-terraform
  namespace: cisco-terraform
spec:
  apiEndpoints:
  - target: organizationmgr
    service:
      scheme: http
      name: organizationmgr
      port: 80
    authType: open
    listenPaths:
    - path: "api/v1/organizations"
      targetSubPath: "api/terraform.cisco.com/v1/organizations" 
      # urlRewrites:
      # - path: "{id}"
      #   method: "GET"
      #   rewriteTo: "api/terraform.cisco.com/"

  - target: agentmgr
    service:
      scheme: http
      name: agentmgr
      port: 80
    authType: open
    listenPaths:
    - path: "api/agent/"
      targetSubPath: "api/terraform.cisco.com/"

  - target: agentpoolmgr
    service:
      scheme: http
      name: agentpoolmgr
      port: 80
    authType: open
    listenPaths:
    - path: "api/v1/agentpool/"
      targetSubPath: "api/terraform.cisco.com/v1/agentpools/id/"
    - path: "api/v1/organization/{org}/agentpools"
      urlRewrites:
      - path: "{org}/agentpools"
        method: "GET"
        matchPattern: "appcenter/cisco/terraform/api/v1/organization/(.*?)/agentpools"
        rewriteTo: "api/terraform.cisco.com/v1/agentpoolList/$1" 
    - path: "api/v1/organization/{org}/agentpool/{agentpool}"
      urlRewrites:
      - path: "{org}/agentpool/{agentpool}"
        method: "GET"
        matchPattern: "appcenter/cisco/terraform/api/v1/organization/(.*)/agentpool/(.*)"
        rewriteTo: "api/terraform.cisco.com/v1/agentpools/organization/$1/agentpool/$2"
      - path: "{org}/agentpool/{agentpool}"
        method: "DELETE"
        matchPattern: "appcenter/cisco/terraform/api/v1/organization/(.*)/agentpool/(.*)"
        rewriteTo: "api/terraform.cisco.com/v1/agentpools/organization/$1/agentpool/$2"
    - path: "api/v1/agentpools"
      targetSubPath: "api/terraform.cisco.com/v1/agentpools"

  - target: credentialsmgr
    service:
      scheme: http
      name: credentialsmgr
      port: 80
    authType: open
    listenPaths:
    - path: "api/credentials/"
      targetSubPath: "api/terraform.cisco.com/"
  - target: ui
    service:
      scheme: http
      name: ui
      port: 3000
    authType: open
    listenPaths:
    - path: "ui/"
    rewrite: ""
