apiVersion: case.cncf.io/v1
kind: App
metadata:
  name: cisco-terraform
spec:
  vendor: cisco
  app: argome
  uiEntrypoint: /appcenter/cisco/argome/ui
  security:
    infraAccess:
      enabled: true
      autoRefresh: true
  deploymentFlavors:
  - name: virtual
    enableInjection: true
    storage:
    - storageID: logger
      size: 2Gi
      diskType: Any
    cpu:
      target:
      - resourceLabel: cpu-argome
        request: "1"
        limit: "2"
    memory:
      target:
      - resourceLabel: memory-argome
        request: 2Gi
        limit: 3Gi
  defaultFlavors:
  - caseDeploymentProfile: physical-standard
    flavor: virtual
  - caseDeploymentProfile: physical-small
    flavor: virtual
  - caseDeploymentProfile: default
    flavor: virtual
---
apiVersion: case.cncf.io/v1
kind: Certificate
metadata:
  name: cisco-terraform
  namespace: cisco-terraform
spec:
  services:
  - name: cisco-terraform-certs
    cn:
      name: cisco-terraform
      addNamespace: false
      addDomain: false
    sans:
      dnsnames:
      - "*"
    extensions:
      basicConstraints:
        ca: false
      extendedKeyUsage:
      - ServerAuth
      - ClientAuth
---
apiVersion: case.cncf.io/v1
kind: Kafka
metadata:
  name: kafka-topics
  namespace: cisco-terraform
spec:
 topics:
 - name: node-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: nodeoper-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: node-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: cluster-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: clusterd-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: organization-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: organization-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agent-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agent-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agentpool-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 - name: agentpool-manager-topic
   partitions: 6
   replicas: 1
   topicProperties:
    retention.ms: 86400
    segment.ms: 86400
 acls:
 - name: node-topic-wr
   cn: cisco-terraform
   topic: node-topic
   op: Write
 - name: node-topic-rd
   cn: cisco-terraform
   topic: node-topic
   op: Read
 - name: nodeoper-topic-wr
   cn: cisco-terraform
   topic: nodeoper-topic
   op: Write
 - name: nodeoper-topic-rd
   cn: cisco-terraform
   topic: nodeoper-topic
   op: Read
 - name: node-manager-topic-wr
   cn: cisco-terraform
   topic: node-manager-topic
   op: Write
 - name: node-manager-topic-rd
   cn: cisco-terraform
   topic: node-manager-topic
   op: Read
 - name: cluster-topic-wr
   cn: cisco-terraform
   topic: cluster-topic
   op: Write
 - name: cluster-topic-rd
   cn: cisco-terraform
   topic: cluster-topic
   op: Read
 - name: clusterd-topic-wr
   cn: cisco-terraform
   topic: clusterd-topic
   op: Write
 - name: clusterd-topic-rd
   cn: cisco-terraform
   topic: clusterd-topic
   op: Read
 - name: organization-topic-wr
   cn: cisco-terraform
   topic: organization-topic
   op: Write
 - name: organization-topic-rd
   cn: cisco-terraform
   topic: organization-topic
   op: Read
 - name: organization-manager-topic-wr
   cn: cisco-terraform
   topic: organization-manager-topic
   op: Write
 - name: organization-manager-topic-rd
   cn: cisco-terraform
   topic: organization-manager-topic
   op: Read
 - name: agent-topic-wr
   cn: cisco-terraform
   topic: agent-topic
   op: Write
 - name: agent-topic-rd
   cn: cisco-terraform
   topic: agent-topic
   op: Read
 - name: agent-manager-topic-wr
   cn: cisco-terraform
   topic: agent-manager-topic
   op: Write
 - name: agent-manager-topic-rd
   cn: cisco-terraform
   topic: agent-manager-topic
   op: Read
 - name: agentpool-topic-wr
   cn: cisco-terraform
   topic: agentpool-topic
   op: Write
 - name: agentpool-topic-rd
   cn: cisco-terraform
   topic: agentpool-topic
   op: Read
 - name: agentpool-manager-topic-wr
   cn: cisco-terraform
   topic: agentpool-manager-topic
   op: Write
 - name: agentpool-manager-topic-rd
   cn: cisco-terraform
   topic: agentpool-manager-topic
   op: Read
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kms
  namespace: cisco-terraform
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8-system-kms
---
apiVersion: case.cncf.io/v1
kind: APIGW
metadata:
  name: cisco-terraform
  namespace: cisco-terraform
spec:
  apiEndpoints:
  - target: nodemgr
    service:
      scheme: http
      name: nodemgr
      port: 80
    authType: open
    listenPaths:
    - path: "/sedgeapi/v1/cisco-terraform/nodemgr"
  - target: clustermgr
    service:
      scheme: http
      name: clustermgr
      port: 80
    authType: open
    listenPaths:
    - path: "/sedgeapi/v1/cisco-terraform/clustermgr"
  - target: organizationmgr
    service:
      scheme: http
      name: organizationmgr
      port: 80
    authType: open
    listenPaths:
    - path: "/sedgeapi/v1/cisco-terraform/organizationmgr"
  - target: agentmgr
    service:
      scheme: http
      name: agentmgr
      port: 80
    authType: open
    listenPaths:
    - path: "/sedgeapi/v1/cisco-terraform/agentmgr"
  - target: agentpoolmgr
    service:
      scheme: http
      name: agentpoolmgr
      port: 80
    authType: open
    listenPaths:
    - path: "/sedgeapi/v1/cisco-terraform/agentpoolmgr"
