apiVersion: case.cncf.io/v1
kind: Feature
metadata:
  name: tfc-agent
  namespace: cisco-terraform
spec:
  configParameters:
    token: ""
    name: ""
    https_proxy: ""
    http_proxy: ""
  resources:
  - on-feature-enable/tfc-agent-deployment.yml